
INSERT INTO INVOICE (INVOICE_CLIENT, VAR_RATE, INVOICE_DATE) VALUES('John Doe', 15, DATE '2015-12-17');
SET @lastid =LAST_INSERT_ID();
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (3, 'Vanilla Cakes', 100.50, @lastid);
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (3, 'Pies', 17.99, @lastid);
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (48, 'Scones', 10.50, @lastid);



INSERT INTO INVOICE (INVOICE_CLIENT, VAR_RATE, INVOICE_DATE) VALUES('Jane Doe', 15, DATE '2017-11-10');
SET @lastid =LAST_INSERT_ID();
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (48, 'Scones', 10.50, @lastid );
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (4, 'Chocolate Cakes', 200.50, @lastid );



INSERT INTO INVOICE (INVOICE_CLIENT, VAR_RATE, INVOICE_DATE) VALUES('Ann Harris', 15, DATE '2014-10-14');
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (5, 'Pies', 17.99, LAST_INSERT_ID());


INSERT INTO INVOICE (INVOICE_CLIENT, VAR_RATE, INVOICE_DATE) VALUES('Dave Smith', 15, DATE '2012-11-23');
INSERT INTO INVOICE_ITEM (INVOICE_QUANTITY, ITEM_DESCRIPTION, UNIT_PRICE, FK_INVOICE_ID)
VALUES (2, 'Loaves', 12.44, LAST_INSERT_ID());
